Fix missing-prototypes
properties.c:207:1: error: 'create_tab' was used with no prototype before its definition [-Werror=missing-prototypes]
os.c:73:1: error: no previous prototype for 'detect_cpu_number' [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>